version: "3"

services:

  attacker:
    image: kalilinux/kali-rolling
    command: sleep infinity

  target:
    image: nginx
    ports:
      - "8081:80"

  firewall:
    image: ubuntu
    command: sleep infinity